Add sprint nights runbook.
pytexas/conference-runbooks pull request #10
Opened 2024-08-29 23:37 UTC by geeksambhu

This PR includes a runbook for sprint nights.

2024-08-30 00:03 UTC, sahmed007 commented
LGTM

2024-08-30 13:23 UTC, dijital20 approved these changes
Looks like a good start. Let's make sure we take another look at it and adjust after we've gotten a few under our belt. :)

2024-09-05 23:37 UTC, MasonEgger requested changes

2024-09-05 23:37 UTC, MasonEgger commented on docs/meetup/runbooks/sprint-nights.md
> +- **Frequency:** Weekly
```suggestion
- **Frequency:** Monthly
```

2024-09-05 23:37 UTC, MasonEgger commented on docs/meetup/runbooks/sprint-nights.md
> +- **Day & Time:** [e.g., Every Thursday at 9 PM]
```suggestion
- **Day & Time:** [e.g., Thursday at 7 PM]
```

2024-09-05 23:48 UTC, MasonEgger approved these changes

2024-09-05 23:48 UTC, merged